### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by NXGHTMVRX** [glaucuslinux/glaucus#1] opened 2019-10-10 15:50 UTC
First of all hello and congrats, impressive work. Your project is closest to what i've been thinking about for quite some time. I have few recommendations for improvements.
1. Vim is great but have too many features to be suckless IMHO. [Kilo](https://github.com/antirez/kilo) has no dependencies and can only save, search, type text . It less than 1000CLOC. If its too simple then you can take a look at [bim](https://github.com/klange/bim), which is simpler and smaller vim clone, but still have many features.
2. Core Utilities: [asmutils](http://asm.sourceforge.net/asmutils.html) is minimal implementation of UNIX utilities written in assembly. There's also [9base](https://git.suckless.org/9base), [busybox](https://git.busybox.net/busybox) and its WIP better rewrite [toybox](https://github.com/landley/toybox).
3. Minimal init system [sinit](https://git.suckless.org/sinit/) and [daemon](https://gist.github.com/rofl0r/6168719)
4. Remove Native Language Support (NLS).
5. Instead of using nnn its simpler and faster for file manager function to write simple script using [fzy](https://github.com/jhawthorn/fzy) or its equivalents.
6. On the [wiki/philosophy page 'Non-GNU'](https://github.com/firasuke/glaucus/wiki/Philosophy), which can't be completely true. I've read that Google is pushing another compiler and trying to get rid of using GCC for kernel. But who knows if it ever happens or at least when. I know that you're working on graphics stack right now so it should sound completely dumb for you to drop all your work. Ideally I recommend to look at something more simplistic, because Linux have millions of LOC.
The simplest of possibilities is one of microkernels. If you thinking about bad performance- looks like that's a myth because Apple is using GNU Mach multiserver microkernels on [every their product](https://en.wikipedia.org/wiki/Mach_%28kernel%29) these days... and IBM Workplace OS too!
Of course I aint mean to use exactly it- there's a plenty of opensource kernels.
Best regards.

**Comment by firasuke** [comment] 2019-10-11 09:02
Thanks for your interest in glaucus! I'm really proud that this project attracted the attention of many enthusiasts. As for your questions:

1. Most of the big programs I've chosen are temporary for now as I wanted to test the limits of the highly custom toolchain and to show that you can still have an extremely minimal base system that uses very few resources while enjoying your fully fledged programs (more resources for your applications). Their are much more lighter alternatives to `vim` which is true (like `vis` for example), but everything other than the base/core image (only includes required `cerata` to boot) is basically optional. You can have `vim`, `vis` or whatever you want (once I'm done with the toolchains that is...). Thanks for recommending `kilo`, I'll definitely check it out, and add it to available `cerata` once I'm done. Perhaps I'll only keep the lightest of programs in the `bennettae` flavour of `glaucus`, since it's supposed to be the lightest.

2. I'm still debating this, as I haven't decided 100% what base utilities I'll be using. I've been considering `toybox` for a while now (and I do not know if I can selectively build certain tools from it as I don't need it entirely). I probably won't swap out most `sbase`, but I'm certainly looking for `ubase` alternatives and I've found many, but none seem complete or are maintained anymore. The closes I found was [utilchest](https://github.com/eltanin-os/utilchest). I've also added many tools from OpenBSD, as they're generally much lighter than `coreutils` but are still much bigger than `sbase` (hence having a mixture of both is important). Offering documentation/manpages is also important when you're providing a base with all these different tools (either on the system itself which I don't recommend, or by reading them online as I'll soon create a separate repo for them).

3. The previous version of `glaucus` called `snail`, had `sinit` implemented. While `sinit` is really lightweight, it isn't ideal, and I've already ported morpheus's and stali's init scripts to `s6-rc` so there's that.

4. I don't think I have that enabled or even planned. I'll only be providing English language support (if you're reading the `ceras` files of the toolchain then please note that they're highly experimental and most likely not synced with my local versions) (plus the repo includes 3 generations of the `ceras` files and I didn't have time to update all of them, so please be careful) (please read [For Awesome Voyagers](https://github.com/firasuke/glaucus/wiki/For-Awesome-Voyagers) for more info, but please beware as it's not that up to date).

5. Again, you can pick and choose whatever you want. My general criteria for picking software was to choose something that is really lightweight, has minimal to no dependencies and is still actively maintained (and of course builds successfully with my custom toolchain). If you think you've found lighter alternatives then please do submit a pull request asking me to merge your `ceras` files, or to create a `ceras` for them. Please keep in mind that there's currently no way to test them as I'm still fixing the toolchain (I'm switching from a `cross and boot`, to a `cross a native and chroot` style and initially I had 4 GCC builds to get everything working, now I've slimmed it down to 2 builds which is much faster and is still completely separated from the host).

6. Oh I created that page really quick, it's not final. I'll change it to `Preferably Non-GNU` to be accurate. Thanks for pointing that out!

Thanks again for showing interest in `glaucus`! Let me know if there's anything else you'd like to ask.

**Comment by NXGHTMVRX** [comment] 2019-10-13 09:01
Please check out [Non-GNU toolchain](https://github.com/tpimh/ngtc) if it may help.

**Comment by firasuke** [comment] 2019-10-13 16:54
That looks really interesting, but unfortunately I won't be adding support for other toolchains any time soon.

I've spent a good amount time experimenting with different toolchains using various components other than GNU. I initially started with `tcc` and `elfutils`/`elftoolchain` but it failed to build a complete `sbase`... I then switched to `pcc` and `elfutils`/`elftoolchain`, and it was much better, as I was able to compile all `sbase` tools but its optimization was really lacking, as the binaries that resulted from `gcc -Os` were smaller than those from `pcc -Os`. I then ditched `elfutils`/`elftoolchain` completely as they don't work well with `musl` and neither includes the entire tools offered by `binutils` (so you'll end up with a mixture of both trying to cover up the basic tools offered by binutils), so I was stuck with `gcc` and `binutils`.

I didn't try `LLVM` as I was trying to limit the amount of cerata using `c++`, but I tested `libc++` once and `libstdc++` was faster (due to regressions in `libc++`). I didn't try `lld` yet, as I was interested in `gold` but, I went back to `bfd/ld` after I knew that `gold` doesn't build with `musl` unless `PIE` is enabled (I didn't plan on using `PIE` early on, but I'm considering it for `thompsoni`).

I might try `lld` in the distant future and maybe give `GOLD` another chance, but I won't be changing the design of the toolchain, especially after I got it working with the optimizations I'm using.

Again, thanks for showing interest in the project! Please do keep your suggestions coming!

**Closed** 2019-12-20 08:18 UTC
Labels: enhancement
